# Generated by Django 3.1.6 on 2021-02-16 22:55

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to=job.models.image_upload),
            preserve_default=False,
        ),
    ]
