# Generated by Django 3.1.6 on 2021-02-16 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='descripition',
            new_name='description',
        ),
    ]
