# Generated by Django 3.1.6 on 2021-02-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210216_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vacancy',
            new_name='vecancy',
        ),
    ]
